### ISSUE TITLE
support for rust language highlighting

### ISSUE THREAD

**Issue by jianshu93** [CodeEditApp/CodeEditLanguages#14]
### Is your feature request related to a problem? Please describe.

support for a very popular language

### Describe the solution you'd like

Rust as the most loved language since 2020, widely used. Add language source for Rust will be very useful, it was considered a good replacement for C++

### Describe alternatives you've considered

nothing, check the Lapce editor (https://lapce.dev)

### Additional context

no

**Comment by lukepistrol** [comment]
Rust should already be implemented. See #10 for missing languages.

**Comment by lukepistrol** [comment]
Closing this since it already is implemented
