### ISSUE TITLE
Syntax Highlighting missing for some file extensions.

### ISSUE THREAD

**Issue by Cubik65536** [CodeEditApp/CodeEditLanguages#18]
I found out that some languages are not fully supported. For example, Java source code has two extensions: `.jav` (which is not that commonly used but is the default for CodeEdit) and `.java`. And it seems that the `.jav` files are not supported by the Syntax Highlighting feature.

**Comment by lukepistrol** [comment]
Should be an easy fix. Will add that now 😉
